import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/index.css";

import Header from "./header";
import Footer from "./footer";
import Container from "./container";
import Sidebar from "./sidebar";

import { Filter } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokemon API Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col h-screen`}>
        <Header />
        <Container className="flex-grow">
          <main className="grid grid-cols-6 gap-4 min-h-full">
            <Sidebar className="col-span-full md:col-span-1">
              <Filter />
            </Sidebar>
            <article className="col-span-full md:col-span-5 bg-slate-100">{children}</article>
          </main>
        </Container>
        <Footer />
      </body>
    </html>
  );
}
